### ISSUE TITLE
API connection failed: TimeoutError()

### ISSUE THREAD

**Issue by thetradingflow** [manhinhang/ib-gateway-docker#58]
Hello,

I followed the instructions exactly: built the docker image and ran the container successfully, but then I am getting the following error in Python when I'm trying to connect ib_insync's IB object:

```python
>>> from ib_insync import IB
>>> ib = IB()
>>> ib.connect(host="localhost", port=4002, clientId=1)
API connection failed: TimeoutError()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/amp/code/ibg/.venv/lib/python3.8/site-packages/ib_insync/ib.py", line 269, in connect
    return self._run(self.connectAsync(
  File "/home/amp/code/ibg/.venv/lib/python3.8/site-packages/ib_insync/ib.py", line 308, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "/home/amp/code/ibg/.venv/lib/python3.8/site-packages/ib_insync/util.py", line 332, in run
    result = loop.run_until_complete(task)
  File "/home/amp/.pyenv/versions/3.8.5/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/amp/code/ibg/.venv/lib/python3.8/site-packages/ib_insync/ib.py", line 1658, in connectAsync
    await self.client.connectAsync(host, port, clientId, timeout)
  File "/home/amp/code/ibg/.venv/lib/python3.8/site-packages/ib_insync/client.py", line 216, in connectAsync
    await asyncio.wait_for(self.apiStart, timeout)
  File "/home/amp/.pyenv/versions/3.8.5/lib/python3.8/asyncio/tasks.py", line 490, in wait_for
    raise exceptions.TimeoutError()
asyncio.exceptions.TimeoutError
```
I tried both the master and develop branches, on both my local computer and a remote server. Same result each time. Any idea what's going wrong here? Many thanks for the repo and your help.

**Comment by manhinhang** [comment]
The client id `1`  reserved for heath check by default.

You can consider change the client id or modify the default value
https://github.com/manhinhang/ib-gateway-docker#other-environment-variable

**Comment by thetradingflow** [comment]
It doesn't seem to be the cause of the problem: I tried it with different clientId values and ran into the same pb.

**Comment by thetradingflow** [comment]
FYI, from within the running container using VSCode, I'm getting a similar error:

```python
root@da1bc74f55da:~# python
Python 3.7.13 (default, May 28 2022, 14:57:08) 
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ib_insync
>>> ib = ib_insync.IB()
>>> ib.connect("localhost", 4002, clientId=103)
API connection failed: TimeoutError()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/ib_insync/ib.py", line 270, in connect
    host, port, clientId, timeout, readonly, account))
  File "/usr/local/lib/python3.7/site-packages/ib_insync/ib.py", line 308, in _run
    return util.run(*awaitables, timeout=self.RequestTimeout)
  File "/usr/local/lib/python3.7/site-packages/ib_insync/util.py", line 332, in run
    result = loop.run_until_complete(task)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/ib_insync/ib.py", line 1626, in connectAsync
    await self.client.connectAsync(host, port, clientId, timeout)
  File "/usr/local/lib/python3.7/site-packages/ib_insync/client.py", line 216, in connectAsync
    await asyncio.wait_for(self.apiStart, timeout)
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
>>> 
```

**Comment by manhinhang** [comment]
> It doesn't seem to be the cause of the problem: I tried it with different clientId values and ran into the same pb.

I think it may something wrong on your development environment because the develop branch was passed sanity test.
https://github.com/manhinhang/ib-gateway-docker/actions/runs/3286886854

You can take a look on this also. This is sanity test workflow.
https://github.com/manhinhang/ib-gateway-docker/blob/4fc8e11bd86333f4dab1214b7758bba220e0e05c/.github/workflows/build-test.yml#L34-L46
